### PR TITLE
Update [MV]_Christmas.pwn

### PR DESCRIPTION
**Pull request by kizule**
Changed from 2017 on 2018 year.

### CODE REVIEW

**Comment by yassinebouelkheir** [comment]
so much improvement, wow!

**Comment by MichaelBelgium** [comment]
Is this necessary?

**Comment by kizule** [comment]
Yes

**Comment by kizule** [comment]
Why you closed?

**Comment by MichaelBelgium** [comment]
Because it doesn't add anything, you're just changing a define which is the purpose of a define depending on the things the server owner wants. Not helpful to do that on git also

**Pull request closed without merging**
